<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
        <i class="fa fa-coffee"></i> New Customer
        </h1>
        <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active"><a href="/customers">Customers</a></li>
        <li class="active">New Customer</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <!-- Horizontal Form -->
                <div class="box">
                    <div class="box-header with-border">
                    <h3 class="box-title">Customer Details</h3>
                    </div>
                    <!-- /.box-header -->
                    <!-- form start -->
                    <form class="form-horizontal">
                        <div class="box-body">
                            <div class="form-group">
                            <label for="inputEmail3" class="col-sm-1 control-label">Email</label>

                            <div class="col-sm-5">
                                <input type="email" class="form-control" id="inputEmail3" placeholder="Email">
                            </div>
                            </div>
                            <div class="form-group">
                            <label for="inputPassword3" class="col-sm-1 control-label">Password</label>

                            <div class="col-sm-5">
                                <input type="password" class="form-control" id="inputPassword3" placeholder="Password">
                            </div>
                            </div>
                            <div class="form-group">
                            <div class="col-sm-offset-1 col-sm-11">
                                <div class="checkbox">
                                <label>
                                    <input type="checkbox"> Remember me
                                </label>
                                </div>
                            </div>
                            </div>
                        </div>
                        <!-- /.box-body -->
                        <div class="box-footer">
                            <button type="submit" class="btn btn-default">Cancel</button>
                            <button type="submit" class="btn btn-info pull-right">Sign in</button>
                        </div>
                        <!-- /.box-footer -->
                    </form>
                </div>                                                                                         
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>  


