<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
            <img src="admin-lte/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
            <p>Alexander Pierce</p>
            <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>
        <!-- search form -->
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
            <input type="text" name="q" class="form-control" placeholder="Search...">
            <span class="input-group-btn">
                    <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                    </button>
                </span>
            </div>
        </form>
        <!-- /.search form -->
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu" data-widget="tree">
            <li class="header">MAIN NAVIGATION
            <li class="<?php echo $this->session->get('active_menu') == 'dashboard' ? 'active' : '' ?>">
                <a href="/dashboard"><i class="fa fa-dashboard"></i><span>Dashboard</span></a>
            </li>                    
            <li class="<?php echo $this->session->get('active_menu') == 'van_inspection' || 
            $this->session->get('active_menu') == 'roll_inspection' || 
            $this->session->get('active_menu') == 'rr_encoding' || 
            $this->session->get('active_menu') == 'rr_review' || 
            $this->session->get('active_menu') == 'rr_approval' ? 'treeview active' : 'treeview' ?>">
                <a href="#">
                    <i class="fa fa-edit"></i><span>Receiving</span>
                    <span class="pull-right-container">
                    <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li class="<?php echo $this->session->get('active_menu') == 'van_inspection' ? 'active' : '' ?>">
                        <a href="/van_inspection"><i class="fa fa-truck"></i> <span>Van Inspection</span></a>
                    </li>    
                    <li class="<?php echo $this->session->get('active_menu') == 'roll_inspection' ? 'active' : '' ?>">
                        <a href="/roll_inspection"><i class="fa fa-flag-o"></i> <span>Roll Inspection</span></a>
                    </li>
                    <li class="<?php echo $this->session->get('active_menu') == 'rr_encoding' ? 'active' : '' ?>">
                        <a href="/rr_encoding">
                            <i class="fa fa-edit"></i>
                            <span>Rec. Rpt. Encoding</span>
                        </a>
                    </li>
                    <li class="<?php echo $this->session->get('active_menu') == 'rr_review' ? 'active' : '' ?>">
                        <a href="/rr_review">
                            <i class="fa fa-clone"></i>
                            <span>Rec. Rpt. Review</span>
                            <span class="pull-right-container">
                                <span class="label label-primary pull-right">4</span>
                            </span>
                        </a>
                    </li>
                    <li class="<?php echo $this->session->get('active_menu') == 'rr_approval' ? 'active' : '' ?>">
                        <a href="/rr_approval">
                            <i class="fa fa-thumbs-o-up"></i>
                            <span>Rec. Rpt. Approval</span>
                            <span class="pull-right-container">
                                <span class="label label-primary pull-right">3</span>
                            </span>
                        </a>
                    </li>        
                </ul>
            </li>    
            <li class="<?php echo $this->session->get('active_menu') == 'warehouses' || 
            $_SESSION['active_menu'] == 'location' ? 'treeview active' : 'treeview' ?>">
                <a href="#">
                    <i class="fa fa-cubes"></i><span>Storage</span>
                    <span class="pull-right-container">
                    <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li class="<?php echo $this->session->get('active_menu') == 'warehouses' ? 'active' : '' ?>">
                        <a href="/warehouses"><i class="fa fa-home"></i><span>Warehouses</span></a>
                    </li>
                    <li class="<?php echo $this->session->get('active_menu') == 'location' ? 'active' : '' ?>">
                        <a href="/suppliers"><i class="fa fa-map-marker"></i><span>Map & Location</span></a>
                    </li>
                </ul>
            </li>            
            <li class="<?php echo $this->session->get('active_menu') == 'warehouses' || 
            $_SESSION['active_menu'] == 'location' ? 'treeview active' : 'treeview' ?>">
                <a href="#">
                    <i class="fa fa-exchange"></i><span>Issuance</span>
                    <span class="pull-right-container">
                    <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li class="<?php echo $this->session->get('active_menu') == 'warehouses' ? 'active' : '' ?>">
                        <a href="/warehouses"><i class="fa fa-home"></i><span>Warehouses</span></a>
                    </li>
                    <li class="<?php echo $this->session->get('active_menu') == 'location' ? 'active' : '' ?>">
                        <a href="/suppliers"><i class="fa fa-map-marker"></i><span>Map & Location</span></a>
                    </li>
                </ul>
            </li>       
            <li class="<?php echo $this->session->get('active_menu') == 'warehouses' || 
            $this->session->get('active_menu') == 'location' ? 'treeview active' : 'treeview' ?>">
                <a href="#">
                    <i class="fa fa-filter"></i><span>Inventory</span>
                    <span class="pull-right-container">
                    <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li class="<?php echo $this->session->get('active_menu') == 'warehouses' ? 'active' : '' ?>">
                        <a href="/warehouses"><i class="fa fa-home"></i><span>Warehouses</span></a>
                    </li>
                    <li class="<?php echo $this->session->get('active_menu') == 'location' ? 'active' : '' ?>">
                        <a href="/suppliers"><i class="fa fa-map-marker"></i><span>Map & Location</span></a>
                    </li>
                </ul>
            </li>                       
            <li class="header">MAINTENANCE</li>                  
            <li class="<?php echo $this->session->get('active_menu') == 'customers' || 
            $this->session->get('active_menu') == 'suppliers' ||
            $this->session->get('active_menu') == 'tollers' ||
            $this->session->get('active_menu') == 'shipping_lines' ||
            $this->session->get('active_menu') == 'truckers' ? 'treeview active' : 'treeview' ?>">
                <a href="#">
                    <i class="fa fa-edit"></i><span>Control Center</span>
                    <span class="pull-right-container">
                    <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li class="<?php echo $this->session->get('active_menu') == 'customers' ? 'active' : '' ?>">
                        <a href="/customers"><i class="fa fa-coffee"></i><span>Customers</span></a>
                    </li>
                    <li class="<?php echo $this->session->get('active_menu') == 'suppliers' ? 'active' : '' ?>">
                        <a href="/suppliers"><i class="fa fa-anchor"></i><span>Suppliers</span></a>
                    </li>
                    <li class="<?php echo $this->session->get('active_menu') == 'tollers' ? 'active' : '' ?>">
                        <a href="/tollers"><i class="fa fa-cube"></i><span>Tollers</span></a>
                    </li>
                    <li class="<?php echo $this->session->get('active_menu') == 'shipping_lines' ? 'active' : '' ?>">
                        <a href="/shipping_lines"><i class="fa fa-ship"></i><span>Shipping Lines</span></a>
                    </li>
                    <li class="<?php echo $this->session->get('active_menu') == 'truckers' ? 'active' : '' ?>">
                        <a href="/truckers"><i class="fa fa-bus"></i><span>Truckers</span></a>
                    </li>
                </ul>
            </li>             
            <li class="<?php echo $this->session->get('active_menu') == 'syslogs' ? 'treeview active' : 'treeview' ?>">
                <a href="#">
                    <i class="fa fa-cogs"></i> <span>Administration</span>
                    <span class="pull-right-container">
                    <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="#"><i class="fa fa-user"></i> <span>Users</span></a></li>
                    <li><a href="#"><i class="fa fa-hand-paper-o"></i> <span>Roles</span></a></li>
                    <li><a href="#"><i class="fa fa-lock"></i> <span>Permission</span></a></li>
                    <li><a href="#"><i class="fa fa-unlock"></i> <span>Reset Password</span></a></li>
                    <li><a href="#"><i class="fa fa-flash"></i> <span>Sessions</span></a></li>
                    <li class="<?php echo $this->session->get('active_menu') == 'syslogs' ? 'active' : '' ?>">
                        <a href="/syslogs"><i class="fa fa-book"></i> <span>System Logs</span></a>
                    </li>
                </ul>
            </li>    
        </ul>        
    </section>
    <!-- /.sidebar -->
  </aside>

